import 'package:flutter/material.dart';
import 'package:healthsphere/screens/Blood/blood_donation_tracker.dart';
import 'package:intl/intl.dart';
import 'package:healthsphere/services/appointment_service.dart';
import 'package:healthsphere/assets/model/appointment.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class BloodDonationConfirmationScreen extends StatelessWidget {
  final DateTime appointmentDate;
  final TimeOfDay appointmentTime;
  final String location;
  final AppointmentService appointmentService = AppointmentService();

  BloodDonationConfirmationScreen({
    Key? key,
    required this.appointmentDate,
    required this.appointmentTime,
    required this.location,
  }) : super(key: key);

  Future<void> _createAppointment() async {
    final DateTime dateTime = DateTime(
      appointmentDate.year,
      appointmentDate.month,
      appointmentDate.day,
      appointmentTime.hour,
      appointmentTime.minute,
    );

    final appointment = Appointment(
      id: '',  // This will be generated by Firestore
      donationType: 'Blood Donation',
      dateTime: dateTime,
      city: 'Your City',  // Replace with actual city
      facility: location,
      location: LatLng(0, 0),  // Replace with actual coordinates
    );

    bool success = await appointmentService.createAppointment(appointment);
    if (success) {
      print('Appointment created successfully');
    } else {
      print('Failed to create appointment');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Confirmation', style: TextStyle(color: Colors.white)),
        backgroundColor: Colors.red,
      ),
      body: Column(
        children: [
          _buildProgressIndicator(context),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircleAvatar(
                    backgroundColor: Colors.green,
                    radius: 40,
                    child: Icon(Icons.check, color: Colors.white, size: 60),
                  ),
                  SizedBox(height: 20),
                  Text(
                    'Registration Confirmed',
                    style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                  ),
                  SizedBox(height: 20),
                  Text(
                    'Your blood donation appointment has been scheduled for:',
                    textAlign: TextAlign.center,
                  ),
                  SizedBox(height: 10),
                  Text(
                    '${DateFormat('dd-MMM-yyyy').format(appointmentDate)} at ${appointmentTime.format(context)}',
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  SizedBox(height: 10),
                  Text(
                    'Location: $location',
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  SizedBox(height: 40),
                  ElevatedButton(
                    child: Text('View All Appointments'),
                    style: ElevatedButton.styleFrom(
                    foregroundColor: Colors.white,
                    backgroundColor: Colors.purple,
                    minimumSize: Size(double.infinity, 50),
                    shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                  onPressed: () async {
                    await _createAppointment();
                    Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(builder: (context) => AppointmentsScreen()),
                  );
                  },
                ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildProgressIndicator(BuildContext context) {
    return Container(
      color: Colors.white,
      padding: EdgeInsets.symmetric(vertical: 16, horizontal: 20),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              _buildProgressStep('Donation Type', true),
              _buildProgressStep('Appointment', true),
              _buildProgressStep('Confirmation', true),
            ],
          ),
          SizedBox(height: 4),
          Container(
            height: 2,
            color: Colors.red,
          ),
        ],
      ),
    );
  }

  Widget _buildProgressStep(String label, bool isActive) {
    return Column(
      children: [
        Container(
          width: 10,
          height: 10,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: isActive ? Colors.red : Colors.grey[300],
          ),
        ),
        SizedBox(height: 4),
        Text(
          label,
          style: TextStyle(
            color: Colors.grey[600],
            fontSize: 12,
          ),
        ),
      ],
    );
  }
}